name       : python3-urwid
version    : 1.3.1
release    : 4
source     :
    - https://github.com/urwid/urwid/archive/release-1.3.1.tar.gz : 42d197063df0ac8e7b6401408fa02ea6b8b1aaf8b8637fbb9c2cd2e0e8f48c3a
license    : LGPL-2.1
component  : programming.python
summary    : Console user interface library for Python
description: |
    Console user interface library for Python.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python3-gobject
    - python-twisted
setup      : |
    %python3_setup
install    : |
    %python3_install
