name       : python3-urwid
version    : 2.1.2
release    : 7
source     :
    - https://github.com/urwid/urwid/archive/refs/tags/release-2.1.2.tar.gz : 366970cabce4a7f70fb4af1d16ac8be23dbcf38f995a20029a4bf32fffe7607d
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Console user interface library for Python
description: |
    Console user interface library for Python.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-gobject
    - python-twisted
setup      : |
    %python3_setup
install    : |
    %python3_install
